// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lbm/wasm/v1/genesis.proto

package lbmtypes

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/line/wasmd/x/wasm/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState - genesis state of x/wasm
type GenesisState struct {
	Params    Params                       `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Codes     []types.Code                 `protobuf:"bytes,2,rep,name=codes,proto3" json:"codes,omitempty"`
	Contracts []types.Contract             `protobuf:"bytes,3,rep,name=contracts,proto3" json:"contracts,omitempty"`
	Sequences []types.Sequence             `protobuf:"bytes,4,rep,name=sequences,proto3" json:"sequences,omitempty"`
	GenMsgs   []types.GenesisState_GenMsgs `protobuf:"bytes,5,rep,name=gen_msgs,json=genMsgs,proto3" json:"gen_msgs,omitempty"`
	// InactiveContractAddresses is a list of contract address that set inactive
	InactiveContractAddresses []string `protobuf:"bytes,6,rep,name=inactive_contract_addresses,json=inactiveContractAddresses,proto3" json:"inactive_contract_address, omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3308f670fed712dc, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetCodes() []types.Code {
	if m != nil {
		return m.Codes
	}
	return nil
}

func (m *GenesisState) GetContracts() []types.Contract {
	if m != nil {
		return m.Contracts
	}
	return nil
}

func (m *GenesisState) GetSequences() []types.Sequence {
	if m != nil {
		return m.Sequences
	}
	return nil
}

func (m *GenesisState) GetGenMsgs() []types.GenesisState_GenMsgs {
	if m != nil {
		return m.GenMsgs
	}
	return nil
}

func (m *GenesisState) GetInactiveContractAddresses() []string {
	if m != nil {
		return m.InactiveContractAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "lbm.wasm.v1.GenesisState")
}

func init() { proto.RegisterFile("lbm/wasm/v1/genesis.proto", fileDescriptor_3308f670fed712dc) }

var fileDescriptor_3308f670fed712dc = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x8a, 0xda, 0x50,
	0x14, 0xc7, 0x93, 0x46, 0x6d, 0x8d, 0x85, 0x42, 0x2c, 0x35, 0x46, 0x88, 0xa1, 0xb4, 0x25, 0x0b,
	0x49, 0xd0, 0x3e, 0x40, 0x69, 0x4a, 0xe9, 0xaa, 0x30, 0x28, 0xb3, 0x19, 0x18, 0x24, 0x1f, 0x97,
	0x6b, 0x20, 0x37, 0x37, 0x93, 0x73, 0x75, 0xc6, 0xb7, 0x98, 0xc7, 0x72, 0xe9, 0x72, 0x56, 0x32,
	0xe8, 0xce, 0x97, 0x98, 0x21, 0x37, 0x1f, 0x06, 0x46, 0x77, 0xc9, 0x39, 0xff, 0xdf, 0xef, 0x70,
	0x0f, 0x47, 0xee, 0x47, 0x1e, 0xb1, 0xef, 0x5d, 0x20, 0xf6, 0x6a, 0x6c, 0x63, 0x14, 0x23, 0x08,
	0xc1, 0x4a, 0x52, 0xca, 0xa8, 0xd2, 0x89, 0x3c, 0x62, 0x65, 0x2d, 0x6b, 0x35, 0xd6, 0x3e, 0x63,
	0x8a, 0x29, 0xaf, 0xdb, 0xd9, 0x57, 0x1e, 0xd1, 0x7a, 0x75, 0x9a, 0xad, 0x13, 0x54, 0xb0, 0x9a,
	0xee, 0x53, 0x20, 0xbc, 0x71, 0xd6, 0xfd, 0xf5, 0x45, 0x92, 0x3f, 0xfe, 0xcb, 0x2b, 0x33, 0xe6,
	0x32, 0xa4, 0x8c, 0xe5, 0x56, 0xe2, 0xa6, 0x2e, 0x01, 0x55, 0x34, 0x44, 0xb3, 0x33, 0xe9, 0x5a,
	0xb5, 0xe9, 0xd6, 0x15, 0x6f, 0x39, 0x8d, 0xcd, 0x6e, 0x28, 0x4c, 0x8b, 0xa0, 0xf2, 0x57, 0x6e,
	0xfa, 0x34, 0x40, 0xa0, 0xbe, 0x33, 0x24, 0xb3, 0x33, 0xf9, 0x62, 0x95, 0x33, 0x2b, 0xec, 0x0f,
	0x0d, 0x90, 0xd3, 0xcb, 0xa0, 0xe3, 0x6e, 0xf8, 0x89, 0x87, 0x47, 0x94, 0x84, 0x0c, 0x91, 0x84,
	0xad, 0xa7, 0x39, 0xad, 0x5c, 0xcb, 0x6d, 0x9f, 0xc6, 0x2c, 0x75, 0x7d, 0x06, 0xaa, 0xc4, 0x55,
	0xda, 0x39, 0x55, 0x1e, 0x71, 0x06, 0x85, 0xae, 0x5b, 0x41, 0x35, 0xe5, 0xc9, 0x94, 0x69, 0x01,
	0xdd, 0x2d, 0x51, 0xec, 0x23, 0x50, 0x1b, 0x97, 0xb4, 0xb3, 0x22, 0x72, 0xd2, 0x56, 0x50, 0x5d,
	0x5b, 0x15, 0x95, 0x5b, 0xf9, 0x03, 0x46, 0xf1, 0x9c, 0x00, 0x06, 0xb5, 0xc9, 0xad, 0x3f, 0xde,
	0x5a, 0xeb, 0x9b, 0xcd, 0x7e, 0xfe, 0x03, 0x06, 0x47, 0x2b, 0x26, 0x28, 0x25, 0x5f, 0x1b, 0xf0,
	0x1e, 0xe7, 0x21, 0x65, 0x21, 0x0f, 0xc2, 0xd8, 0xf5, 0x59, 0xb8, 0x42, 0xf3, 0xf2, 0x2d, 0x73,
	0x37, 0x08, 0x52, 0x04, 0x80, 0x40, 0x6d, 0x19, 0x92, 0xd9, 0x76, 0xcc, 0xe3, 0x6e, 0xf8, 0xed,
	0x62, 0x6c, 0x64, 0x9c, 0xbc, 0xfd, 0x32, 0x55, 0xae, 0xef, 0x77, 0xa9, 0x72, 0x7e, 0x6d, 0xf6,
	0xba, 0xb8, 0xdd, 0xeb, 0xe2, 0xf3, 0x5e, 0x17, 0x1f, 0x0f, 0xba, 0xb0, 0x3d, 0xe8, 0xc2, 0xd3,
	0x41, 0x17, 0x6e, 0xbe, 0xe3, 0x90, 0x2d, 0x96, 0x9e, 0xe5, 0x53, 0x62, 0x47, 0x61, 0x8c, 0xf8,
	0x09, 0x05, 0xf6, 0x43, 0x7e, 0x4a, 0x91, 0x47, 0xf8, 0xa1, 0x79, 0x2d, 0x7e, 0x49, 0x3f, 0x5f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xad, 0x7e, 0xaa, 0xc2, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InactiveContractAddresses) > 0 {
		for iNdEx := len(m.InactiveContractAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.InactiveContractAddresses[iNdEx])
			copy(dAtA[i:], m.InactiveContractAddresses[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.InactiveContractAddresses[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.GenMsgs) > 0 {
		for iNdEx := len(m.GenMsgs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GenMsgs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Sequences) > 0 {
		for iNdEx := len(m.Sequences) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sequences[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Contracts) > 0 {
		for iNdEx := len(m.Contracts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Contracts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Codes) > 0 {
		for iNdEx := len(m.Codes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Codes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Codes) > 0 {
		for _, e := range m.Codes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Contracts) > 0 {
		for _, e := range m.Contracts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Sequences) > 0 {
		for _, e := range m.Sequences {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GenMsgs) > 0 {
		for _, e := range m.GenMsgs {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.InactiveContractAddresses) > 0 {
		for _, s := range m.InactiveContractAddresses {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Codes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Codes = append(m.Codes, types.Code{})
			if err := m.Codes[len(m.Codes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contracts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contracts = append(m.Contracts, types.Contract{})
			if err := m.Contracts[len(m.Contracts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequences", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequences = append(m.Sequences, types.Sequence{})
			if err := m.Sequences[len(m.Sequences)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenMsgs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenMsgs = append(m.GenMsgs, types.GenesisState_GenMsgs{})
			if err := m.GenMsgs[len(m.GenMsgs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InactiveContractAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InactiveContractAddresses = append(m.InactiveContractAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
