name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.18
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Clear cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          run-id: ${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: check pwd
        run: |
          ls -al
      - uses: golangci/golangci-lint-action@master
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.50.1
          args: --timeout 10m
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: env.GIT_DIFF
